#!/bin/bash
set -e
set -u

start_url='http://ftp.nhc.noaa.gov/atcf/adv/'
name='atcf-adv-mirror'
cache=${PWD}/cache
logs=${PWD}/logs
ts=$(date -u +%s-%F)
logfile=$logs/mirror-$ts

wget_opts=(
    # --no-config
    --no-verbose
    # --quiet

    --directory-prefix="$cache"
    --output-file="$logfile"
    # --rejected-log="$logs/rejected-$ts"

    --force-directories
    --timestamping
    --recursive
    --level=inf
    --no-remove-listing
    --no-parent

    --reject-regex='\?.=.;.=.$'

    --wait=0.1                  # wait SECONDS between retrievals
    --quota=20m                 # set retrieval quota to NUMBER
    # --limit-rate=RATE           limit download rate to RATE
    # --unlink                    remove file before clobber
    # --no-xattr                  turn off storage of metadata in extended file attributes
)


mkdir -p "$cache" "$logs"

wget "${wget_opts[@]}" "$start_url"

sed -n -e 's/^.*"\([^"]*_info\.xml\)".*$/\1/p' -- "$logfile"
